### ISSUE TITLE
SPI mode support

### ISSUE THREAD

**Issue by hasenbanck** [stm32duino/stm32flash#1]
Currently I'm working on supporting the SPI mode of the bootloader ([link to the branch](https://github.com/hasenbanck/stm32flash/tree/spi-mode)).

Maybe you are interested in later including this feature in this branch. But before that, I need to get it working.

@fpistm, maybe you have some ideas or could query about this problem:

I added the SPI backend to the stm32flash utility and the communication between a Linux host with SPIDEV device and a STM32722ZE is working fine. I can init the bootloader and get past the first "ACKNOWLEDGE" (Figure 1 and Figure 3 in AN4286).

I send the ACK byte back to the slave and want to send my first command to the bootloader (Get Version / 0x01 with prepended SOF byte). It seems that the bootloader on my board is not working as specified in the AN4286, since it doesn't reply with an ACK/NACK to this command (for at least 10 seconds). I attached a screenshot of captured traffic of that part of the communication. The bootloader will continue to send 0xA5 and not sending an ACK/NACK. The bootloader also seem to send a 0x11 directly after sending the SYNC byte (0x5A) in this capture.

Is the maybe an updated SPI protocol version? I have Rev 3 (20.10.2016) of the document (AN4286).

Capture of the part in question:
![ds1z_quickprint6](https://user-images.githubusercontent.com/12084860/47953677-23406c80-df81-11e8-8077-d7af6bdb4d10.png)

**Comment by hasenbanck** [comment]
Okay, I think that 0x11 is something that was in some buffer or something.

I fixed the problem by fixing some bugs in stm32flash and my implementation (I skipped the ACK reply somehow, which came much later then expected).

So you can right now ignore my question, but I will let this issue open, to report, when I finished the SPI implementation and may need some testers.

**Comment by fpistm** [comment]
Hi @hasenbanck 
it seems there is an updated document:
https://www.st.com/content/ccc/resource/technical/document/application_note/7a/8a/0a/8f/8f/38/47/c0/DM00081379.pdf/files/DM00081379.pdf/jcr:content/translations/en.DM00081379.pdf
but it seems only applicable product update.

**Comment by hasenbanck** [comment]
Thanks for the updated document. I finished the SPI backend and it seems to work fine at 8 MHz on my crappy test setup with breadboard connections. Reading/Writing/Memory CRC all seem to work fine on my tests.

**Comment by hasenbanck** [comment]
Opened #2
